version: '3'

services:
  sensu-backend:
    image: sensu/sensu:6.10.0
    command: sensu-backend start
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - sensu-backend-data:/var/lib/sensu
    networks:
      - sensu

  sensu-agent:
    image: sensu/sensu:6.10.0
    command: >
      sensu-agent start
      --backend-url ws://sensu-backend:8081
      --deregister
      --keepalive-interval 5
      --keepalive-warning-timeout 10
      --subscriptions linux
    ports:
      - "3030:3030"
    networks:
      - sensu

volumes:
  sensu-backend-data:

networks:
  sensu:
    driver: bridge
